# Generated by Django 4.1.3 on 2022-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImagen', models.CharField(default='https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png', max_length=150)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=30)),
                ('latitud', models.CharField(max_length=30)),
                ('altitud', models.CharField(max_length=30)),
                ('metrosCuadrados', models.CharField(max_length=30)),
            ],
        ),
    ]
