# Generated by Django 4.1.3 on 2022-11-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='altitud',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='metrosCuadrados',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='urlImagen',
        ),
    ]
