# Generated by Django 4.1.2 on 2022-11-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arboles', '0002_arbol_metroscuadrados'),
        ('equipos', '0003_remove_equipo_personas_persona_equipo'),
        ('proyectos', '0002_remove_proyectos_altitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('avance', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('presupuesto_arboles', models.IntegerField()),
                ('presupuesto', models.FloatField()),
                ('material_disponible', models.IntegerField()),
                ('ubicacion', models.TextField()),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pausa', 'Pausa'), ('Completado', 'Completado')], default='Activo', max_length=40)),
                ('tipo_suelo', models.CharField(choices=[('Sustrato', 'Sustrato'), ('Caliza', 'Caliza'), ('Cuarcita', 'Cuarcita'), ('Arcilla', 'Arcilla'), ('Turba', 'Turba')], max_length=30)),
                ('metros_cuadrados', models.FloatField()),
                ('clima', models.CharField(choices=[('Frio', 'Frio'), ('Calido', 'Calido'), ('Humedo', 'Humedo'), ('Soleado', 'Soleado'), ('Seco', 'Seco')], max_length=30)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.equipo')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.persona')),
                ('tipo_arbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arboles.arbol')),
            ],
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
    ]
