# Generated by Django 4.1.2 on 2022-11-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_delete_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='urlImagen',
            field=models.CharField(default='https://www.bbva.com/wp-content/uploads/2021/11/reforestacio%CC%81n_plantar-arboles-sostenibilidad-cuidado-medioambiente-planeta-bosques--1024x629.jpg', max_length=120),
        ),
    ]
