# Generated by Django 4.1.2 on 2022-11-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_limite',
            field=models.DateField(),
        ),
    ]
