# Generated by Django 4.1.2 on 2022-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyecto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='avance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='material_disponible',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto_arboles',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
