# Generated by Django 4.1.2 on 2022-11-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImagen', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('ecosistema', models.CharField(max_length=30)),
                ('nombreCientifico', models.CharField(max_length=50)),
                ('altura', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
