# Generated by Django 4.1.2 on 2022-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arboles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='metrosCuadrados',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
