# Generated by Django 4.1.2 on 2022-11-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImagen', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Staff', 'Staff'), ('Supervisor', 'Supervisor'), ('Lider', 'Lider'), ('Coordinador', 'Coordinador')], default='Staff', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('personas', models.ManyToManyField(to='equipos.persona')),
            ],
        ),
    ]
